### PR TITLE
add support for nodejs crypto in browserCrypto engine

### PR DESCRIPTION
**Pull request by AccaliaDeElementia**
preferentially uses global crypto.getRandomValues when available falling back to crypto.randomBytes otherwise

resolves ckknight/random-js#16

### CODE REVIEW

**Comment by AccaliaDeElementia** [comment]
huh.... node 0.10 complains about that?

i'll have that fixed in a jiffy.

**Comment by LiamKarlMitchell** [comment]
Is there a technical reason why this may have not been merged in after all this time?

**Comment by AccaliaDeElementia** [comment]
None that I know of, if there is an objection to the PR by @ckknight I would be more than happy to hear and address it.

**Comment by dhessler** [comment]
any updates here? would be great to have nodejs crypto support

**Comment by ckknight** [comment]
In light of the new API of v2.0.0, I believe the best way to support this will be by having a module that can be imported like `random-js/nodeCrypto` that exports a node-compatible crypto-based engine. This wouldn’t be exported by the main module, in order to maintain the loose browser compatibility.

This will be part of the official v2.0.0 release, and thank you for the effort that was put in for this.

**Comment by ckknight** [comment]
I decided to expose this on the main module as `nodeCrypto`.

```
const { nodeCrypto } = require('random-js');

nodeCrypto.next(); // uses require('crypto').randomBytes under-the-hood
```

This is available with v2.0.0-rc2.

**Pull request closed without merging**
