### PR TITLE
Add getIndex() method to mt19937 engine

### PR DESCRIPTION
**Pull request by pariser**
If you're using the mt19937 engine, you should now be able to do
the following:

    var mt = Random.engines.mt19937();

    // Use an already known seed
    mt.seedWithArray(seed);

    // use the generator some number of times...
    mt();
    mt();

    // figure out how many times you've used it (should return 2)
    mt.getIndex();

Then, you should be able to resume generating from the same exact
sequence where you left off...

    var mt = Random.engines.mt19937();

    // Use the same seed
    mt.seedWithArray(seed);

    // Skip back to where you were by discarding your previous
    // number of generated numbers (2 comes from the above example)
    mt.discard(2);

    // Get the next random number
    mt();

There's no comparable mechanism to do the same thing with the `nativeMath` or `browserCrypto`, and thus there's nothing to implement for these engines.

### CODE REVIEW

**Comment by ckknight** [comment]
Do you really want the index or do you want the amount of times that it has been used? Which can be over 624.

If you request too many times, having a low index won't allow you to discard to the necessary point, you would need to discard the full amount.

**Comment by pariser** [comment]
Ah, makes sense - I really want the number of times that the generator has been used - lemme submit a better patch patch then...

**Comment by pariser** [comment]
Should be fixed at this point - let me know what you think.

**Comment by ckknight** [comment]
This looks good, but needs tests. I may get around to implementing some for this, but I can't ethically merge until then.

**Comment by pariser** [comment]
I did write some tests, starting at https://github.com/pariser/random-js/blob/mt-with-index/spec/engines.mt19937Spec.js#L31. Github just suppresses the diff for `spec/engines.mt19937Spec.js` for some reason. Let me know if you think these tests are/would be sufficient, or if you think it needs additional coverage.

**Pull request merged**
